name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest

      # ===== DEBUG SECRET LENGTH =====
      - name: Debug kube secret
        run: |
          echo "Secret length:"
          echo "${{ secrets.KUBECONFIG_DATA }}" | wc -c

      # ===== SETUP KUBECONFIG =====
      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

          echo "=== FILE SIZE ==="
          ls -l $HOME/.kube/config

          echo "=== FILE CONTENT (first 20 lines) ==="
          head -n 20 $HOME/.kube/config

      # ===== TEST KUBE ACCESS =====
      - name: Test Kubernetes Access
        run: |
          kubectl config view
          kubectl get nodes

      # ===== DEPLOY =====
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment devops-app

